---
layout:     post
title:      错误处理
subtitle:	 
date:       2020-06-01
author:     Neil
header-img: img/post-bg-coffee.jpeg
catalog: 	 true
tags:
    - 错误处理
---

最近遇到一个下载完成处理资源的需求，比如有MD5校验，包资源解压等

如下是下载zip资源的流程图

![](/img/local/DownloadFlowChart.png)

增量指的是新旧资源包新增的部分,我们这里称为增量包。旧资源包与新增部分合并后生成新的资源包，新生成的资源包为下一次的基准包。

查看流程图可以发现这里有MD5的校验、有包的合并、还有包的解压，其中我在使用包合并时候，如果我传入一个无效的资源包，甚至有crash的风险，这里我们如果处理错误以及crash呢？

我这里定义了一个函数

```
- (BOOL)dealZip... error:(NSError **)error{

}
```

上述是一个伪代码，是一个处理下载资源的函数，当校验、合并或者解压一个环节出现错误时候，返回fasle，并将错误内容赋予给函数的参数error，可以查看error内容具体错误是什么。

错误内容可以这么去定义

首先定义错误Domain和Code

```
extern NSString *const KSCourseResourceDownloadErrorDomain;
typedef NS_ENUM(NSInteger, KSCourseResourceDownloadErrorCode) {
    KSCourseResourceDownloadErrorCodeMD5CheckFail     = -1,
    KSCourseResourceDownloadErrorCodeFileNotFound   = -2,
    KSCourseResourceDownloadErrorCodeMergePatchFail   = -3,
    KSCourseResourceDownloadErrorCodeUnzipFail   = -4,
};
```

然后使用NSError的方法生成error对象，因为参数传入的是error的地址，所以*error可以直接修改error地址指向的内容，使得可以通过参数读取错误的内容

```
@try {
    [KSLocalDataTool bspatch:basePath newPath:newPath patchPath:zipPath];
} @catch (NSException *exception) {
    *error = [NSError errorWithDomain:KSCourseResourceDownloadErrorDomain
                                 code:KSCourseResourceDownloadErrorCodeMergePatchFail
                             userInfo:exception.userInfo];
    return false;
} @finally {
    
}
```

仔细看这里还有 `@try{} @catch{}` 的处理，虽然前面做了资源的校验和资源是否存在的判断，但是这里为了保证不出现新崩溃，使用 `@try{} @catch{}`来处理，降低应用崩溃的风险

写到这里，文章已经讲到怎样使用`NSError`错误和 `@try{} @catch{}` 来处理错误或者可能的崩溃，那么函数为什么这么定义呢？（凡事多问几个为什么，容易找到事物的本质，也是之前文章提到认知圈思维-黄金思维why-what-how）

因为这里文件的操作比较多，有文件合并和文件解压，都会出现错误，如果直接返回错误，用户还需要判断错误的内容是否是空来知道文件操作是否成功，没有直接返回`BOOL`来的简明，如果需要错误具体的内容可以定义错误的对象，并传入其地址作为参数，就可以得到错误的具体内容了，如果不需要直接传入`nil`即可

写到这里基本上写完了错误处理的整体思路，后续持续更新，多谢关注






